[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
heapless.workspace = true
blake3.workspace = true
rand.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
serde-big-array.workspace = true
bincode.workspace = true
